services:
  sb4camunda8:
    container_name: sb4camunda8
    image: sb4camunda8
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    command: --spring.profiles.active=prod
